// <auto-generated />
using System;
using MealMaster.DAL.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealMaster.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealMaster.Domain.Entities.CuisineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CuisineTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b6541e6-5b6b-4a4f-a132-66bb747887ec"),
                            IsDeleted = false,
                            Name = "Итальянская"
                        },
                        new
                        {
                            Id = new Guid("6294bd11-b8d4-4fb1-9ecf-12010cfc44c3"),
                            IsDeleted = false,
                            Name = "Русская"
                        },
                        new
                        {
                            Id = new Guid("bdaa918d-819c-4ca0-be25-91baf1cf0326"),
                            IsDeleted = false,
                            Name = "Белорусская"
                        },
                        new
                        {
                            Id = new Guid("ba55b0eb-b230-4aab-843e-87f2e32a1b98"),
                            IsDeleted = false,
                            Name = "Французская"
                        },
                        new
                        {
                            Id = new Guid("d3e94e6f-7234-4f58-800c-309a888891f8"),
                            IsDeleted = false,
                            Name = "Китайская"
                        },
                        new
                        {
                            Id = new Guid("11cdaf91-5b19-46b6-bb2f-816d06cdeb89"),
                            IsDeleted = false,
                            Name = "Японская"
                        },
                        new
                        {
                            Id = new Guid("5b4bd099-1366-43d3-9fac-cafb74c32d25"),
                            IsDeleted = false,
                            Name = "Мексиканская"
                        },
                        new
                        {
                            Id = new Guid("e975b9ea-acaa-4c16-b44a-c77a066e59cb"),
                            IsDeleted = false,
                            Name = "Испанская"
                        },
                        new
                        {
                            Id = new Guid("8689e938-9b77-47af-9313-f9832cd4b251"),
                            IsDeleted = false,
                            Name = "Американская"
                        },
                        new
                        {
                            Id = new Guid("ca3aec54-a6b6-47bb-8fd4-c142d685b091"),
                            IsDeleted = false,
                            Name = "Тайская"
                        });
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.DietaryRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DietaryRestrictions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b805814e-fe99-4b1c-984f-9078b74a54e7"),
                            IsDeleted = false,
                            Name = "Диабетическое"
                        },
                        new
                        {
                            Id = new Guid("c17c7d88-e32c-4d26-9365-90e46d867437"),
                            IsDeleted = false,
                            Name = "Вегетарианское"
                        },
                        new
                        {
                            Id = new Guid("fc2915fc-a62f-4cc4-8ae8-2c4648db7a67"),
                            IsDeleted = false,
                            Name = "Безглютеновое"
                        },
                        new
                        {
                            Id = new Guid("d275e3a7-979b-40a6-b546-17fddb8054fd"),
                            IsDeleted = false,
                            Name = "Кето"
                        },
                        new
                        {
                            Id = new Guid("e67fb98a-894b-4924-9188-221562818c33"),
                            IsDeleted = false,
                            Name = "Безлактозное"
                        },
                        new
                        {
                            Id = new Guid("9e8fd88a-75f3-4802-9a63-4d28f32b0333"),
                            IsDeleted = false,
                            Name = "Веганское"
                        },
                        new
                        {
                            Id = new Guid("188a4031-96fd-4864-98a9-bf339f1c012f"),
                            IsDeleted = false,
                            Name = "Палео"
                        });
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MealCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.MenuHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MenuHistories");
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<int>("PortionSize")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MenuId", "RecipeId")
                        .IsUnique();

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b7ad343-97ed-4129-badf-d9f4d847827d"),
                            IsDeleted = false,
                            Name = "Картофель"
                        },
                        new
                        {
                            Id = new Guid("882726b3-73c2-4829-82b7-f71c80cbed8f"),
                            IsDeleted = false,
                            Name = "Курица"
                        },
                        new
                        {
                            Id = new Guid("95be5955-d504-47c5-9c88-d50c3d245a33"),
                            IsDeleted = false,
                            Name = "Говядина"
                        },
                        new
                        {
                            Id = new Guid("0edf6bfd-99f9-4109-bc49-2d0c7529e0c2"),
                            IsDeleted = false,
                            Name = "Свинина"
                        },
                        new
                        {
                            Id = new Guid("4730e71e-8bd0-488a-b169-a4dcf56139cd"),
                            IsDeleted = false,
                            Name = "Морковь"
                        },
                        new
                        {
                            Id = new Guid("0baf1228-8dbb-41e6-a685-69f9588402fe"),
                            IsDeleted = false,
                            Name = "Лук"
                        },
                        new
                        {
                            Id = new Guid("53a0ad48-8eef-4420-9fad-1268886fd021"),
                            IsDeleted = false,
                            Name = "Чеснок"
                        },
                        new
                        {
                            Id = new Guid("5a7f5ecf-2a25-4777-b89d-326d373b4410"),
                            IsDeleted = false,
                            Name = "Яйца"
                        },
                        new
                        {
                            Id = new Guid("117ed9cd-9692-4abc-b1b8-cc1c14c0367f"),
                            IsDeleted = false,
                            Name = "Молоко"
                        },
                        new
                        {
                            Id = new Guid("70437b7d-18d8-4bc0-9fdb-84492ceb7afe"),
                            IsDeleted = false,
                            Name = "Мука"
                        },
                        new
                        {
                            Id = new Guid("44d58684-d746-465d-baaa-be066f42f5bb"),
                            IsDeleted = false,
                            Name = "Сыр"
                        },
                        new
                        {
                            Id = new Guid("038ab599-86b0-4f5b-850b-40c3b3bcd7ec"),
                            IsDeleted = false,
                            Name = "Рис"
                        },
                        new
                        {
                            Id = new Guid("8869314d-5031-4425-ab8b-fa9ea37a1464"),
                            IsDeleted = false,
                            Name = "Паста"
                        },
                        new
                        {
                            Id = new Guid("c81eeff4-e1d3-4ed5-a4b1-4bab466fe5e3"),
                            IsDeleted = false,
                            Name = "Помидоры"
                        },
                        new
                        {
                            Id = new Guid("e029e174-9a92-4d0a-885f-da3e14894daf"),
                            IsDeleted = false,
                            Name = "Огурцы"
                        },
                        new
                        {
                            Id = new Guid("1eb80aa0-6be7-4d08-8d0a-2fa98eeab8ac"),
                            IsDeleted = false,
                            Name = "Перец"
                        },
                        new
                        {
                            Id = new Guid("b1ef8dce-8805-4d5f-bdd8-0e48c24b94fd"),
                            IsDeleted = false,
                            Name = "Сметана"
                        },
                        new
                        {
                            Id = new Guid("9e052544-b5d0-41b3-9025-e3dfded68b70"),
                            IsDeleted = false,
                            Name = "Масло сливочное"
                        },
                        new
                        {
                            Id = new Guid("65fec9d1-3989-4978-9f5b-85562c568590"),
                            IsDeleted = false,
                            Name = "Капуста"
                        },
                        new
                        {
                            Id = new Guid("f6c30c5b-e2a0-4c4c-bf4d-a32f1f7082f2"),
                            IsDeleted = false,
                            Name = "Гречка"
                        },
                        new
                        {
                            Id = new Guid("53d59b79-7206-47c0-867e-c3b286041188"),
                            IsDeleted = false,
                            Name = "Бекон"
                        },
                        new
                        {
                            Id = new Guid("5925fd38-194d-4b18-98d5-631b06c10137"),
                            IsDeleted = false,
                            Name = "Шпинат"
                        },
                        new
                        {
                            Id = new Guid("4451aa95-54b5-431f-9472-03bc05e40cdf"),
                            IsDeleted = false,
                            Name = "Грибы"
                        },
                        new
                        {
                            Id = new Guid("6dbd8b04-fbff-4394-8308-ec5160036e24"),
                            IsDeleted = false,
                            Name = "Брокколи"
                        },
                        new
                        {
                            Id = new Guid("8b38f129-f683-4d34-a3a4-1667526b288b"),
                            IsDeleted = false,
                            Name = "Авокадо"
                        },
                        new
                        {
                            Id = new Guid("f835cd42-a68b-46ce-943e-b1b17c0e292e"),
                            IsDeleted = false,
                            Name = "Креветки"
                        },
                        new
                        {
                            Id = new Guid("0558b532-6e97-4f35-a54b-b6bec5045abc"),
                            IsDeleted = false,
                            Name = "Тунец"
                        },
                        new
                        {
                            Id = new Guid("fc6e8836-bab8-4132-984b-4ea216d0b930"),
                            IsDeleted = false,
                            Name = "Лосось"
                        });
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuisineTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("RestrictionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CuisineTypeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.RecipeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RecipeProducts");
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.UserRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RestrictionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RestrictionId")
                        .IsUnique();

                    b.ToTable("UserRestrictions");
                });

            modelBuilder.Entity("MealMaster.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("MealMaster.Domain.Entities.CuisineType", null)
                        .WithMany()
                        .HasForeignKey("CuisineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
